name: Create release

on:
  push:
    tags:
      - 'v*' # Triggers on any tag starting with 'v'

permissions:
  contents: write # Grants write permissions to create the release

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest # Or another suitable runner
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install 

      - name: Build
        run: npm run build 

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided GitHub token
          TAG: ${{ github.ref_name }} # The name of the pushed tag
        run: |
          gh release upload "${TAG#v}" dist/echo-circuit.es.js dist/echo-circuit.umd.js dist/echo-circuit.css